
---
title: "Respirometry Trails for Summer Krill 2019"
output:
 html_document:
    df_print: paged
    code_folding: hide
    toc: TRUE
    toc_depth: 4
    toc_float: true
    theme: journal
    highlight: zenburn
    smart: false
editor_options: 
  chunk_output_type: inline
---


Hello World

Author: OA Lab, NWFSC, Kate Rovinski
Title:Function Learning for Real this Time
Date: December 2020


# Version Check
```{r 0.1 Version Check , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
## Version Check
#********************************* 
R.version

```


# Function Learning for Real this Time


```{r 0.0 Libraries, echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
## Libraries
#********************************* 
library(dpylr)
library(ggplot2)

```





```{r}
#**************E*N*D*************# 
#*********************************
## END OF SCRIPT | END OF DOCUMENT 
#*********************************
```


## END OF SCRIPT | END OF DOCUMENT