
---
title: "Function Learning for Real this Time, More Complicated"
output:
 html_document:
    df_print: paged
    code_folding: hide
    toc: TRUE
    toc_depth: 4
    toc_float: true
    theme: cerulean
    highlight: haddock
    smart: false
editor_options: 
  chunk_output_type: inline
---


Hello World

Author: OA Lab, NWFSC, Kate Rovinski
Title:Function Learning for Real this Time
Date: December 2020


# Version Check
```{r 0.1 Version Check , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
## Version Check
#********************************* 
R.version

```


# Function Learning for Real this Time- a bit more complicated

*Videos I used*
[HefinRhys|Writing functions in R|2017Video](https://youtu.be/ffPeac3BigM)



```{r 0.0 Libraries, echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
## Libraries
#********************************* 
# library(dpylr)
# library(ggplot2)

```


# 1.0 Call for Normal Distribution
```{r 1.0 Call for Normal Distribution, warning=FALSE}
#*********************************
## 1.0 Call for Normal Distribution
#********************************* 

normalDist <- rnorm(1000, 0, 1)
mean(normalDist)
hist(normalDist)

nrmDSTplot1 <- hist(normalDist)
nrmDSTplot1

#if curious about function histogram
# ?hist

# --- Exploring Histogram Function

# hist(x, ...)
# Usage for the Funct

#if an argument specified with an = sign it's mandatory supply
# if an argument has a default value with an equals sign, you the user, don't have to enter it/supply it


# hist(x, breaks = "Sturges",
#      freq = NULL, probability = !freq,
#      include.lowest = TRUE, right = TRUE,
#      density = NULL, angle = 45, col = NULL, border = NULL,
#      main = paste("Histogram of" , xname),
#      xlim = range(breaks), ylim = NULL,
#      xlab = xname, ylab,
#      axes = TRUE, plot = TRUE, labels = FALSE,
#      nclass = NULL, warn.unused = TRUE, ...)


# Exploring a default value 
# hist(x, breaks = "Sturges",

hist(normalDist, breaks = 50)

nrmDSTplot2 <- hist(normalDist, breaks = 50)
nrmDSTplot2

```




# 2.0 Hello Function
```{r 2.0 Hello Function, warning=FALSE}
#*********************************
## 2.0 Hello Function
#********************************* 
#
# Functions don't have to take arguments
# They can return a value whenever they are called 

# # HELLO FUNCTION ' ' ' ' ' ' ' '
sayhello <- function() {
"hello"
  }
  # we have created a function that needs no arguments

sayhello

sayhello()

```


# 3.0 Hello Function- with outputs
```{r 3.0 Hello Function- with outputs, warning=FALSE}
#*********************************
## 3.0 Hello Function- with outputs
#********************************* 
#

# # Saying HELLO FUNCTION ' ' ' ' '
sayinghello <- function(name){
  paste("hello", name)
}

greet <- sayinghello("Kate")
# call the greet object
greet



```



# 4.0 Function with Special Arguments 
```{r 4.0 Function with Special Arguments, warning=FALSE}
#*********************************
##  4.0 Function with Special Arguments
#********************************* 

expo <- function(x, power = 2) {
  hist(x^power)
}
  
# the power = 2 tells r that this is an optional argument 


expo(normalDist)

```




















```{r}
#**************E*N*D*************# 
#*********************************
## END OF SCRIPT | END OF DOCUMENT 
#*********************************
```


## END OF SCRIPT | END OF DOCUMENT